browser/scripts/patterns.js
doc/main/sweet.html
doc/main/sweet.md
lib/patterns.js
src/patterns.js
test/test_bad_patterns.js
test/test_macro_patterns.js

In the following example, `$a` gets bound to the second token, throwing away the first binding:
```js
macro foo {
rule { $a $a } => { alert($a); }
}
foo "hello" "world"
// expands to
alert('world');
```
As a reference, if you do the same thing in Racket, it will fail at compile time:
```scheme
(define-syntax foo
(syntax-rules ()
((_ a a)
(printf "~a\n" (list a)))))
;; ERROR:  syntax-rules: variable used twice in pattern in: a
```
The behavior in Racket is definitely more intuitive than the current behavior in sweet.js.  However, I would actually propose that repeating a variable in a pattern should not throw an error but should actually try to match with the current binding.  The idea is that if you repeat a variable, you also want the matched tokens to repeat.
```js
foo "hello" "world" …
```

Repeating variables in a macro pattern should repeat matched tokens

---

browser/break.txt
browser/editor.html
browser/scripts/editor.js
browser/scripts/expander.js
browser/scripts/patterns.js
browser/scripts/reverse.js
browser/scripts/sjs.js
browser/solarized.css
lib/expander.js
lib/patterns.js
lib/reverse.js
lib/sjs.js
src/expander.js
src/patterns.js
src/reverse.js
src/sjs.js
test/test_macro_patterns.js
test/test_reverse.js

For rule macros, it is possible to automatically refactor code with macros by using the template (body of the rule macro) to match syntax and replace it with the corresponding macro invocation based on the pattern.  This pull request adds support for this type of "macrofication" refactoring.  In order to use this features, I added a command line flag (-r) and integrated the refactoring into the sweet.js editor.  Using the editor is definitely the preferred way of refactoring as it highlights the code and let's you chose which code to replace by a macro:
The macrofication option in the editor is off by default but seems to work pretty good.  Limitations are some special kind of "expr" pattern classes and locally scoped macro definitions.  Also, the highlighting is mutually exclusive with …

Automatic Macro Refactoring (Macrofication)

---

src/enforester.js
src/shift-reader.js
test/test_macro_expansion.js

Allow macro names to be punctuators. Also allows tokenization of `@` (this was legal pre-1.0). Allows you to do fun things like:
```js
syntax @ = function (ctx) {
return #`this`;
}
@
```

Allow macro names to be punctuators

---

src/macro-context.js
test/assertions.js
test/test_enforest.js
test/test_macro_context.js

Exposes the macro context name via a method.
```javascript
syntax foo = ctx => {
ctx.name().val() // foo
//...
}
foo 42
```
Implements #538

Macro context name via method

---

doc/1.0/reference.adoc
doc/1.0/reference.html
src/enforester.js
src/macro-context.js
test/test_macro_context.js
test/test_macro_expansion.js

Re-submit of #552.
This PR adds `.reset` which allows the context to be returned to its initial state. It also removes the enforestation logic from `.next` to `.expand`.

Add reset and expand to MacroContext

---

doc/1.0/reference.adoc
doc/1.0/tutorial.adoc
src/enforester.js
src/errors.js
src/macro-context.js
test/test_macro_expansion.js

You can now match against more grammar productions with the `MacroContext::expand` method:
```js
syntax m = ctx => {
let expr = ctx.expand('BinaryExpression');
// ...
}
syntax n = ctx => {
let ident = ctx.expand('IdentifierExpression');
// ...
}
m foo() + 100 - [1, 2, 3]   // <- everything is matched
n foo() + 100 - [1, 2, 3]   // <- only `foo` is matched
```

Add ability to match more terms in MacroContext::expand

---

doc/1.0/reference.adoc
src/macro-context.js
src/syntax.js
test/test_macro_expansion.js
test/test_syntax.js

For some reason, I had become convinced that the only way to make the `Syntax` static `from*` methods available to compiletime code was via modules. But in fact they can, and actually should, be put on `Syntax` instances. This would let you do cool things like:
```js
syntax to_str = ctx => {
let argStr = ctx.next().value.val();
let dummy = #`here`.get(0);
return #`${dummy.fromString(argStr)}`;
}
let s = to_str foo
// expands to:
// let s = 'foo'
```
The reason we actually want to make `from*` instance methods is that most of the time when creating a new syntax object you need to re-use an existing syntax object's lexical context (the third argument to the static `Syntax.from` method). Having these methods as instance methods means you get the lexical context stealing behavior "for free".

Add from* syntax methods to syntax instances

---

macros/spec.js
src/shift-reader.js
src/syntax.js
src/term-spec.js
test/test_asi.js

Template literals were missing source location, which cased errors on code like:
```js
function f () {
return `foo`;
}
```
since enforesting `return` requres checking the lineNumber on the next token.

Fix missing source location info on template literals

---

doc/1.0/tutorial.adoc
doc/1.0/tutorial.html

It’s basically `framwork -> framework`. I think I only needed to change the .adoc file, but I was not 100% sure (and I couldn’t find a _contributing.md_ file on this repo), so I just went ahead.

Small typo fix

---

doc/1.0/reference.adoc
src/macro-context.js
test/test_macro_context.js
test/test_macro_expansion.js

The ability to move back one term can be implemented as a utility function. Unfortunately the time complexity is O(n) in the number of syntax items.
To my mind a big reason to have this ability is to expand a term based on the type of syntax read:
```js
import { prev } from './utils' for syntax;
syntax m = ctx => {
ctx.next() // eatThis
let stx = ctx.next().value;
let ret;
if(stx.isIdentifier()) {
ret = #`${stx}`;
} else if(stx.isDelimiter() && stx.isBracket()) {
prev(ctx); // <- call to prev
ret = #`${ctx.expand('ArrayExpression')}`;
}
return ret;
}
m eatThis foo; // foo
m eatThis [1,2,3] // [1,2,3]
```
But the same thing can be accomplished with lookahead:
```js
import { lookahead } from './utils' for syntax;
syntax m = ctx => {
ctx.next(); // eatThis
let stx = lookahead(ctx); // <- …
```

Add the ability to create a reset point on a macro context

---

bin/sjs
package.json

Give a nice error message and exit when using old versions of node.

Enforce node version; fixes #536

---

src/enforester.js
test/expressions/new-expression.js

This fix handles new expressions with member expressions as callees.

fixes #592

---

src/enforester.js
src/parse-reducer.js
src/term-expander.js
test/assertions.js
test/expressions/new-expression.js
test/expressions/this-expression.js
test/statements/for-statement.js
test/statements/try-catch-statement.js

While attempting to replicate the performance test https://github.com/shapesecurity/shift-parser-js/blob/ce88859a4636ba1d0d06d7d3e0d89ade767c8233/profile.js I discovered a bug with the enforestation of `this` in new expressions.

Fix parse errors

---

src/load-syntax.js
src/macro-context.js
test/test-asi.js
test/test-macro-context.js
test/test-macro-expansion.js

Addresses #615.
Dropping `SyntaxOrTermWrapper` and replacing its `.inner` method with a `contextify` (strawman name but I kind of like it) method on `MacroContext`.
This is doubling down on the breaking change of everything being a `Term`.

Drop wrapper in macro context

---

src/node-loader.js

By default `resolve` only looks for files with `.js` as an extension. This adds the ability for the `NodeLoader` to enable additional extensions to resolve.

Add ability to select extensions to resolve

---

src/node-loader.js

Enables:
```js
syntax m = ctx => {
console.log(process.env);
return #`1`;
}
m
```

Add console and process to global in a macro definition

---

src/syntax.js
test/test-macro-expansion.js

This is a hack. I'll open an issue outlining what I think is the better solution.

Have Syntax::fromParens return RawDelimiter; fixes #625

---

package.json
src/enforester.js
src/macro-context.js
src/reader/default-readtable.js
src/reader/read-dispatch.js
src/reader/read-template.js
src/reader/token-reader.js
src/reader/utils.js
src/scope-reducer.js
src/tokens.js
test.js
test/test-default-readtable.js
test/test-macro-context.js
test/test-reader-extensions.js
test/test-reader.js
yarn.lock

Ok, so I think my original plan of doing the term/syntax unification right now is not going to work. At least not the approach of doing it all in one big push.
So I'm going to break it down into smaller refactorings. This PR will just decouple the reader from syntax/terms.
It also probably isn't worth holding up 3.0 to wait for the unification so I'll start cleaning up things to get that out the door.

Decouple reader from syntax/terms

---

.eslintignore
src/enforester.js
test/assertions.js
test/test-parse.js

```javascript
{
foo = bar()
baz = foo
}
// and
{
foo = new bar()
baz = foo
}
```
both result in:
```javascript
{
foo = baz = foo;
}
```
This is because after enforestation of either a `CallExpression` or a `NewExpression` the while loop in `enforestLeftHandSideExpression` was either entered (in the case of `NewExpression`) or continued (in the case of `CallExpression`).
This PR fixes that by breaking or returning respectively.

Fix IdentiferExpression encountered after New/CallExpression

---

package.json

In the Gitter room we got a question about using sweet in the browser. The editor already uses a webpack bundle 😄. But it's AMD ☹️.
I changed the output type to `umd` to support all of the things. Now it should work with require.js, as a global and in node.

Change webpack output from AMD to UMD to support global.sweet

---

src/macro-context.js
test/unit/test-macro-context.js

Wrap MacroContext::name in RawSyntax

---

src/enforester.js
src/syntax.js
test/unit/test-operators.js

Custom operators were being recursively defined which caused:
```js
operator + left 2 = (left, right) => {
return #`${left} + ${right}`;
}
```
to go into an infinite loop. Not good, this PR fixes that.

Prevent operators from being recursively defined

---

doc/1.0/reference.adoc
doc/1.0/tutorial.adoc

To avoid more silly mistakes like https://github.com/sweet-js/sweet.js/issues/679#issuecomment-294068431 I've added semicolons to the end of all function expressions defining macros in the code samples.
I think a lot of people who try out Sweet start by copy/pasting from the tutorial. Currently, if they're going to be bitten by `[...]` and `(...)` following a `syntax`, `syntaxrec` or `operator` definition. This should ease some frustration.

Add semicolons after function expressions in docs

---

bin/sjs

- use realpath as in #649 
- set NodeLoader's baseDir to cwd (this was totally wrong!)

Handle relative paths on CLI better

---

src/syntax.js
test/unit/test-modules.js
test/unit/test-syntax.js

Disabling this for now because the ambiguous scopeset error is being triggered in some basic cases where it should not (#693 in particular). Actually fixing the underlying hygiene bug requires a bit more thought and time. 
I think the real problem has to do with how the module inside edge scope is being added but it's going to take me a little while to work though how to fix it.

Temporarily disable ambiguous scopesets error

---

.eslintrc
src/reader/read-identifier.js
src/reader/utils.js
test/parser/test-run-test262.js
test/unit/test-default-readtable.js

Fixes #702.
This used to throw the reader into an infinite loop. It made several test262 tests unrunnable.

Throw when encountering an invalid identifier as the first char

---

src/enforester.js
src/module-visitor.js
src/sweet-spec-utils.js
test/unit/test-modules.js

A useful feature that people might actually like.

Fix exporting/importing custom operators

---

package.json
src/sweet-module.js
src/sweet-to-shift-reducer.js
test/assertions.js
test/parser/__snapshots__/test-ast.js.snap
test/parser/test-ast.js
yarn.lock

No reason for the `'lang sweet.js'` directive to be in the codegen'd output so omit it.
Also make all directives actually directives in the shift output AST so they don't get wrapped in parens.

Do not include lang directive in output

---

src/sweet-module.js
src/sweet-to-shift-reducer.js
test/parser/__snapshots__/test-ast.js.snap
test/parser/test-ast.js

Export declarations were not being included in the compiled output due to a too aggressive approach to preparing modules for eval inside of sweet. The PR fixes that in a hacky way, the module handling stuff needs a rewrite.
Don't merge this just yet, I want to add a snapshot test as in #718 but need to figure out why travis is complaining first.

Fix missing export in compiled output

---

src/sweet-module.js
src/sweet-to-shift-reducer.js
test/parser/__snapshots__/test-ast.js.snap
test/parser/test-ast.js

Fixes #722.
Compiling `export var x` now compiles to `var x_1; export { x_1 as x }`.

Do not resolve exportedNames

---

src/node-loader.js
src/sweet-module.js
src/sweet-to-shift-reducer.js
src/token-expander.js
test/parser/test-run-test262.js

fixes #727
Imports for runtime values should no longer be dropped during codegen. This is a hacky fix but I've got a few yaks to go before we can do it the right way.

Keep imports for runtime values

---

package-lock.json
package.json
src/module-visitor.js
src/sweet-loader.js
src/sweet.js
src/token-expander.js
test/modules/_helpers.js
test/modules/test-expanding-cjs.js

fixes #736
Turns out there was an even simpler repro:
```js
// mod.js
export var x = 1;
// main.js
import { x } from './mod.js';
```
The issue is the design of module hygiene assumes bundling of all the modules #662 and so sets up a forwarding binding for each imported name. This greatly simplifies module bundling (just emit each module and bindings take care of themselves) but since we don't have bundling yet we run into this problem.
The solution is a little hacky, only add forwarding bindings to import names when:
- not the entrypoint or
- importing for phase > 0 or
- importing a compiletime binding
Don't merge just yet, I still need to add tests.

Handle forwarding bindings better

---

src/enforester.js
src/env.js
src/operators.js
src/term-expander.js
src/tokens.js
src/transforms.js
test/parser/__snapshots__/test-ast.js.snap
test/parser/test-ast.js

This PR adds support in sweet's parser but shift-codegen doesn't support async/await yet so it won't be usable until support has been added there.

Add parsing support for async/await
